"""Checksum format I/O: .md5, .sha1, .sfv (CRC32), .ffp (FLAC fingerprint)."""

import hashlib
import re
import subprocess
import zlib
from pathlib import Path
from typing import Iterable

CHUNK = 1 << 20  # 1 MiB


def md5sum(path: Path) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK), b""):
            h.update(chunk)
    return h.hexdigest()


def sha1sum(path: Path) -> str:
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK), b""):
            h.update(chunk)
    return h.hexdigest()


def crc32(path: Path) -> str:
    c = 0
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK), b""):
            c = zlib.crc32(chunk, c)
    return f"{c & 0xFFFFFFFF:08X}"


def flac_fingerprint(path: Path, metaflac_exe: Path) -> str:
    """Read the MD5 of unencoded audio samples from a FLAC's STREAMINFO."""
    r = subprocess.run(
        [str(metaflac_exe), "--show-md5sum", str(path)],
        capture_output=True, text=True, timeout=30,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )
    out = (r.stdout or "").strip()
    if not re.fullmatch(r"[0-9a-fA-F]{32}", out):
        raise RuntimeError(f"unexpected metaflac output for {path.name}: {out!r}")
    return out.lower()


# ---------------------------------------------------------------
# Writers
# ---------------------------------------------------------------

def write_md5(entries: list[tuple[str, str]], out_path: Path) -> None:
    """coreutils format: '<hash>  <filename>\\n' (two spaces)."""
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        for name, h in entries:
            f.write(f"{h}  {name}\n")


def write_sha1(entries: list[tuple[str, str]], out_path: Path) -> None:
    write_md5(entries, out_path)  # same on-disk layout


def write_sfv(entries: list[tuple[str, str]], out_path: Path) -> None:
    """SFV format: '<filename> <CRC32-uppercase>\\n', with ; comments allowed."""
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("; Generated by Trader's Little Jedi\n")
        for name, h in entries:
            f.write(f"{name} {h.upper()}\n")


def write_ffp(entries: list[tuple[str, str]], out_path: Path) -> None:
    """FFP format: '<filename>:<md5-of-audio-samples>\\n'."""
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        for name, h in entries:
            f.write(f"{name}:{h.lower()}\n")


# ---------------------------------------------------------------
# Parsers (for verification)
# ---------------------------------------------------------------

def parse_md5(path: Path) -> list[tuple[str, str]]:
    """Returns list of (filename, expected_hash)."""
    out: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        # Accept '<hash>  <name>' OR '<hash> *<name>' (binary marker)
        m = re.match(r"([0-9a-fA-F]{32})\s+\*?(.+)$", line)
        if m:
            out.append((m.group(2).strip(), m.group(1).lower()))
    return out


def parse_sha1(path: Path) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        m = re.match(r"([0-9a-fA-F]{40})\s+\*?(.+)$", line)
        if m:
            out.append((m.group(2).strip(), m.group(1).lower()))
    return out


def parse_sfv(path: Path) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        # last whitespace-separated token is the CRC
        m = re.match(r"(.+?)\s+([0-9a-fA-F]{8})\s*$", line)
        if m:
            out.append((m.group(1).strip(), m.group(2).upper()))
    return out


def parse_ffp(path: Path) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if ":" not in line:
            continue
        name, _, h = line.rpartition(":")
        h = h.strip().lower()
        if re.fullmatch(r"[0-9a-fA-F]{32}", h):
            out.append((name.strip(), h))
    return out


# ---------------------------------------------------------------
# Format detection
# ---------------------------------------------------------------

FORMATS = ("md5", "sha1", "sfv", "ffp")


def detect_format(path: Path) -> str | None:
    ext = path.suffix.lower().lstrip(".")
    if ext in FORMATS:
        return ext
    return None
