"""Shared pytest fixtures for the AudioHelper test suite.

Pure-logic tests need nothing. Tests that touch real audio use the
``synth_flac`` / ``synth_wav`` fixtures, which generate a tiny file with
ffmpeg and skip automatically when ffmpeg isn't available.
"""
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

# Make the package importable when running `pytest` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def _have(exe: str) -> bool:
    return shutil.which(exe) is not None


HAVE_FFMPEG = _have("ffmpeg") and _have("ffprobe")

try:
    import mutagen  # noqa: F401
    HAVE_MUTAGEN = True
except ImportError:
    HAVE_MUTAGEN = False


@pytest.fixture
def synth_wav(tmp_path):
    """A 2-second silent stereo WAV generated by ffmpeg."""
    if not HAVE_FFMPEG:
        pytest.skip("ffmpeg not available")
    out = tmp_path / "tone.wav"
    subprocess.run(
        ["ffmpeg", "-y", "-hide_banner", "-f", "lavfi",
         "-i", "sine=frequency=440:duration=2", "-ac", "2",
         "-c:a", "pcm_s16le", str(out)],
        capture_output=True, check=True)
    return out


@pytest.fixture
def synth_flac(tmp_path):
    """A 2-second sine FLAC generated by ffmpeg (no tags, no cover)."""
    if not HAVE_FFMPEG:
        pytest.skip("ffmpeg not available")
    out = tmp_path / "tone.flac"
    subprocess.run(
        ["ffmpeg", "-y", "-hide_banner", "-f", "lavfi",
         "-i", "sine=frequency=440:duration=2", "-ac", "2",
         "-c:a", "flac", str(out)],
        capture_output=True, check=True)
    return out
